name: {{name}}

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  collection: ^1.17.0
  flame: ^1.6.0
  flame_forge2d: ^0.12.5
  flame_lint: ^0.2.0
  flame_svg: ^1.7.1
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  logger: ^1.1.0

dev_dependencies:
  flame_test: ^1.9.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/audio/
