include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: true

dart_code_metrics:
  anti-patterns:
    - long-method
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
    - lib/presentation/navigation/auto_router.gr.dart
  rules-exclude:
    - test/**
    - lib/presentation/navigation/auto_router.gr.dart
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
